### ISSUE TITLE
Нарушение принципа подстановки

### ISSUE THREAD

**Issue by loyd** [B-Vladi/Response#20]
Библиотека нарушает [принцип подстановки Лисков](https://en.wikipedia.org/wiki/Liskov_substitution_principle), что демонстрирует следующий пример:

```javascript
var q = new R.Queue;
q.push(function () {
    var r = R.resolve(10);
    return r.map(function () { return [1,2,3] });
}, 'lol');

q.start();
console.log(q.getResult('lol'));
```

Вывод ожидаем:
```
[1, 2, 3]
```

Если заменить на подкласс `Response` — `Queue`, то поведение меняется:
```javascript
var R = require('Response');

var q = new R.Queue;
q.push(function () {
    var r = new R.Queue([R.resolve(10)], true);
    return r.map(function () { return [1,2,3] });
}, 'lol');

q.start();
console.log(q.getResult('lol'));
```

То вывод следующий:
```
{}
```

Это мешает строить интерфейсы: если мы заявляем, что функция возвращает `Response`, то вызывающий код не может работать с этим объектом как с `Response`, поскольку поведение для подкласса меняется.

**Comment by B-Vladi** [comment]
В твоем примере ты не подменяешь объект класса `Queue` на объект `Response` в вызывающем коде:
```js
var R = require('Response');

var q = new R.Queue;
q.push(..., 'lol');
q.start();
console.log(q.getResult('lol'));
```
И в том и в другом случае ты работаешь с `Queue`. У тебя баг в строчке:
```js
return r.map(function () { return [1,2,3] });
```

**Comment by loyd** [comment]
Эм, нет, подожди. В **функции** у  меня Response меняется на Queue и внешнее поведение меняется.

**Comment by loyd** [comment]
Переоткрой issue или создам новый.

**Comment by loyd** [comment]
Переоткрой

**Comment by B-Vladi** [comment]
Да, поведение меняется, смирись.

**Comment by loyd** [comment]
Ну тогда либо документируй, что твоя библиотека ~~говно~~ не используема для потсроения абстракций, либо оставь открытым issue.
