### ISSUE TITLE
Кастомные ошибки в reject

### ISSUE THREAD

**Issue by corpix** [B-Vladi/Response#3]
Давай уберем https://github.com/B-Vladi/Response/blob/master/Response.js#L385
Это мешает созданию кастомных ошибок. Особенно ошибок с кастомными полями.

**Comment by B-Vladi** [comment]
Как именно это мешает?

**Comment by B-Vladi** [comment]
Fixed

**Comment by corpix** [comment]
:+1:

**Comment by corpix** [comment]
Эх, нет, не пофикшено.
Вот здесь https://github.com/B-Vladi/Response/blob/master/Response.js#L1262 похоже должно быть `!(value instanceof Error)`.

Я пытаюсь добиться того чтобы атрибут `code` сохранялся. Сейчас это не так:
```
> new GeolocationError('test', 1)
Object { message: "test", code: 1 }
> toError(new GeolocationError('test', 1)).code
undefined
```

**Comment by B-Vladi** [comment]
Fixed =)
